# Generated by Django 3.1.7 on 2021-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JugueteriaApp', '0002_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCate', models.CharField(max_length=20)),
            ],
        ),
    ]
